### ISSUE TITLE
Provide a client for interacting with a JSON API server?

### ISSUE THREAD

**Issue by mglaman** [f3ath/json-api-dart#1]
It looks like https://github.com/qurami/jsonapi_client_dart is outdated, and this package is much more verbose in handling JSON API documents.

The only "problem" is that a client is missing. A client would allow streamlining requesting documents and collections (ie: includes, filters, etc.)

Would you be open to a contribution adding a client? Or is that out of scope of this package?

**Comment by f3ath** [comment]
v0.3.0 now has a Client, so closing this one.
