### ISSUE TITLE
Decode/Encode only Usage

### ISSUE THREAD

**Issue by EmirBostanci** [f3ath/json-api-dart#104]
Greetings! First of all, thanks for caring the community and making your library open source!

My question is, is there a way to use decoding/encoding functionality without using http request functions? 

Since example code is not defining this future, i wanted to ask for help :) 

Thanks!

**Comment by f3ath** [comment]
hi @EmirBostanci. If I understand the question correctly, you want to use [fromJson()](https://github.com/f3ath/json-api-dart/blob/b8e1dfdd3f87aed590cae6b7c47d0b9502cb4ab4/lib/src/document/resource_object.dart#L39) and [toJson()](https://github.com/f3ath/json-api-dart/blob/b8e1dfdd3f87aed590cae6b7c47d0b9502cb4ab4/lib/src/document/resource_object.dart#L73) conversion methods on the document objects. What is your use case?

**Comment by EmirBostanci** [comment]
My use case is, i only want to flatten/normalize json:api spec like objects. I want to use my own network/request management structure, but looking for an implementation to convert json objects. like this [Japx](https://github.com/infinum/Japx) library does. @f3ath

**Comment by f3ath** [comment]
Yes, in this case I'd expect the methods I mentioned above to fit your needs. Let me know if you find them (not) useful.

**Comment by EmirBostanci** [comment]
Can you please prepare documentation, example or tests about these methods and their usages? @f3ath 
Thanks for help!
