### ISSUE TITLE
Add client in constructor in DisposableHandler for convenience

### ISSUE THREAD

**Issue by dan12411** [f3ath/json-api-dart#116]
Hi guys, is appropriate to add client in constructor in DisposableHandler for convenience usage?

For example,
```dart

class DisposableHandler implements HttpHandler {
  DisposableHandler(this.client);

  Client? client;

  @override
  Future<HttpResponse> handle(HttpRequest request) async {
    final httpClient = client ?? Client();
    try {
      return await PersistentHandler(httpClient).handle(request);
    } finally {
      httpClient.close();
    }
  }
}
```

**Comment by dan12411** [comment]
Another question is `PersistentHandler` did not implement  HttpHandler by default, is a bug?

[PersistentHandler](https://github.com/f3ath/json-api-dart/blob/4c2dbe9c9c0751f434b646501079f0068867027d/lib/src/client/persistent_handler.dart)

**Comment by f3ath** [comment]
It definitely is a bug. PersistentHandler is meant to implement that interface and I think it is also the answer to the first question.

**Comment by f3ath** [comment]
5.0.2 is published. Do you think PersistentHandler can help you now?

**Comment by dan12411** [comment]
@f3ath yes, thanks!
