### ISSUE TITLE
Content-Type has charset=utf-8 which seems not to be standard for json:api

### ISSUE THREAD

**Issue by franckstifler** [f3ath/json-api-dart#129]
Here are the request headers being sent to my server. It rejects this request due to charset=utf-8 being appended to the Content-Type header.
```
 req_headers: [
    {"accept", "application/vnd.api+json"},
    {"accept-encoding", "gzip"},
    {"content-type", "application/vnd.api+json; charset=utf-8"},
    {"host", "localhost:4000"},
    {"user-agent", "Dart/2.18 (dart:io)"}
  ]
```

**Comment by f3ath** [comment]
Can you please add some steps to reproduce the issue?

**Comment by franckstifler** [comment]
I have a standard app, setup as mentioned in the docs.
```
const baseUrl = "http://localhost:4000";
final uriDesign = StandardUriDesign(Uri.parse(baseUrl));
final client = RoutingClient(uriDesign);
final response = await client.fetchCollection('annonces', headers: headers);
print(response);
```
Is my server not compliant to the json:api standard? or this additional charset header is ok?

**Comment by f3ath** [comment]
It is fair to expect the client not to add any extra headers or at least give you control over it. I will take a deeper look today.

**Comment by franckstifler** [comment]
https://jsonapi.org/format/#media-type-parameters
From the documentation it seems json:api only supports `profile` and `ext`.
https://jsonapi.org/format/#content-negotiation-servers this is why I receive the error from my server.

**Comment by f3ath** [comment]
The extra headers seem to be added by the Dart HTTP client itself. I see no reason why it would set the `Content-Type` for a GET request. Gonna research this a bit deeper.

**Comment by f3ath** [comment]
The HTTP client sets `Content-Type` every time the request body is set, even if the body is empty: https://github.com/dart-lang/http/blob/88f6fc6edc8b941b4a0acc1bd6de51625b54bcc3/pkgs/http/lib/src/request.dart#L91

I believe this is an upstream issue and should be reported/fixed. Meanwhile we can add a workaround in the our code.

**Comment by f3ath** [comment]
https://github.com/dart-lang/http/issues/841

**Comment by franckstifler** [comment]
Thanks for the follow up. I've set the header manually on the server while waiting this to get fixed.
