### ISSUE TITLE
Compound documents support

### ISSUE THREAD

**Issue by f3ath** [f3ath/json-api-dart#19]

**Comment by jaysson** [comment]
I am new to JSON API standard. If I understand properly, it just needs to parse and set `included` property in `CollectionDocument.fromJson`.

```
final data = json['data'];
      if (data is List) {
        final links = Link.parseMap(json['links'] ?? {});
        final included = json['included'].map(ResourceObject.fromJson).toList();
        return CollectionDocument(data.map(ResourceObject.fromJson).toList(),
            self: links['self'], pagination: Pagination.fromMap(links), included: included);
      }
```
Is there more to it? Currently I am trying to use this library, and access to included resources is all that is missing for my use case. I can send a PR for this.

**Comment by f3ath** [comment]
Hey, thanks for your interest. This library is under active development and I'm changing the internal API pretty much randomly until I find a decent approach. Meanwhile please try version `0.0.1` (not a joke) which relies on another library which has support for compound documents. Just make sure you have `json_api: 0.0.1` and not `json_api: ^0.0.1`. Seriously, please LMK if it works for you. If not, we'll figure something out.

https://github.com/f3ath/json-api-dart/tree/0.0.1

**Comment by f3ath** [comment]
Hey @jaysson thanks for your interest. This library is under heavy development and I'm changing the API pretty much randomly until I find a decent approach. Meanwhile I suggest you try version 0.0.1 (not a joke) which relies on another library which supports compound documents. Note that the 0.0.1 API is quite different, so make sure you have `json_api: 0.0.1` and not `json_api: ^0.0.1` so does not upgrade the version unexpectedly.

Here's the link: https://pub.dartlang.org/packages/json_api/versions/0.0.1

**Comment by f3ath** [comment]
@jaysson The client now supports compound documents. Would you mind trying it out?

https://pub.dartlang.org/packages/json_api/versions/0.4.0

**Comment by f3ath** [comment]
Here's an example https://github.com/f3ath/json-api-dart/blob/6eba655b03b6573989f7a9b40caf3c55c09537d6/test/functional/fetch_test.dart#L90
