### ISSUE TITLE
How do I access "included"

### ISSUE THREAD

**Issue by frazras** [f3ath/json-api-dart#47]
The JSON:API specification as implemented in the Drupal JSON:API module attaches images files to the `included` key in the JSON:API document. However, I have not seen how to access it using the methods available in the API. 

I saw it mentioned by @mglaman in https://github.com/f3ath/json-api-dart/issues/1#issue-396785210 but it didn't seem like it made it into the client.

Is there a way to do this with the current client?

**Comment by f3ath** [comment]
Hi @frazras. This included resources are fetched into `List<ResourceObject> included` member of the Document's Primary Data. 
```dart
      final r = await client.fetchResource(uri);
      print(r.data.included.length); // Number of included resources
      print(r.data.included.first);
```
Here's an [example](https://github.com/f3ath/json-api-dart/blob/master/test/functional/fetch_test.dart#L117) in the tests.

**Comment by f3ath** [comment]
I assume this resolved.

**Comment by eskalera** [comment]
Sorry for reopening, but shouldn't includes be present in the response only when requested from client? Why are there includes when requesting only for this:

`http://localhost:8080/companies/1`

Also, I can't find a way to build the query with an include of my choice other than 

`urlDesign.collection('objects').replace(queryParameters: {'include': 'relatedObject'});`
