### ISSUE TITLE
Easier logging

### ISSUE THREAD

**Issue by uddyami** [f3ath/json-api-dart#60]
When i'm trying to Alice https://pub.dev/packages/alice#-readme-tab-
this is following exception
```
Try changing the type of the parameter, or casting the argument to 'Response/*2*/'.
```
 Can some one help show some working examples around this ?

**Comment by karapetov** [comment]
Hi @uddyami. I'm not sure what it has to do with this library. Could you please give me specific detail on what exactly you're doing? Also please provide the logs and stack traces you have.

**Comment by f3ath** [comment]
Hi @uddyami. I'm not sure what it has to do with this library. Could you please give me specific detail on what exactly you're doing? Also please provide the logs and stack traces you have.

**Comment by uddyami** [comment]
I'm trying to add logging to see raw request/ response. Alice adds logging and works on vanilla httpClient requests. From the api i expected to use it with JsonApiClient as well. But the type exception is something i'm getting stuck with.

this is an example for alice usage
```
httpClient
	.getUrl(Uri.parse("https://jsonplaceholder.typicode.com/posts"))
	.then((request) async {
		alice.onHttpClientRequest(request);
		var httpResponse = await request.close();
		var responseBody = await httpResponse.transform(utf8.decoder).join();
		alice.onHttpClientResponse(httpResponse, request, body: responseBody);
 });
```

**Comment by f3ath** [comment]
I'll try to figure it out. Meanwhile would you mind making an example dart code I could use to reproduce the issue?

**Comment by uddyami** [comment]
sure i'll try and create something with example code

**Comment by uddyami** [comment]
```
import 'package:http/http.dart';
import 'package:json_api/json_api.dart';
import 'package:alice/alice.dart';
void main() async {
  final httpClient = Client();
  final jsonApiClient = JsonApiClient(httpClient);
  Alice alice = Alice(showNotification: true);
  final companiesUri = Uri.parse('http://localhost:8080/companies');
  final response = await jsonApiClient.fetchCollection(companiesUri).then((request) async {
		alice.onHttpClientRequest(request);
		var httpResponse = await request.close();
		var responseBody = await httpResponse.transform(utf8.decoder).join();
		alice.onHttpClientResponse(httpResponse, request, body: responseBody);
 });
  
  httpClient.close();
  print('Status: ${response.status}');
  print('Headers: ${response.headers}');

  final resource = response.data.unwrap().first;

  print('The collection page size is ${response.data.collection.length}');
  print('The first element is ${resource}');
  print('Attributes:');
  resource.attributes.forEach((k, v) => print('$k=$v'));
  print('Relationships:');
  resource.toOne.forEach((k, v) => print('$k=$v'));
  resource.toMany.forEach((k, v) => print('$k=$v'));
}
```

these lines have the error
```
alice.onHttpClientRequest(request);
alice.onHttpClientResponse(httpResponse, request, body: responseBody);
```

**Comment by f3ath** [comment]
Well, this one is explainable. `fetchCollection(companiesUri)` returns an instance of [Response](https://pub.dev/documentation/json_api/latest/client/Response-class.html), and not an instance of httpRequest which you're trying to send to Alice. I will add event hooks so you'd be able to hook up the logging more easily.

**Comment by f3ath** [comment]
@uddyami I have added the [onHttpCall](https://pub.dev/documentation/json_api/latest/client/JsonApiClient-class.html) callback. You can use it to pass the request/response objects to Alice. Please let me know if it helps or if you need more details on it.

**Comment by uddyami** [comment]
I works perfectly! I love the fact you add it at client level. 
This is how i used it 
```
final jsonApiClient = JsonApiClient(httpClient,  onHttpCall: (req, resp) {
  print("request : ${req.method} ${req.url} \n ${req.headers}  \n ${req.body}");
  print("response: ${resp.headers} \n ${resp.body}");
  });
```

EDIT 
actually something is off now. After api call is done and logged the response doesn't seem to work. Maybe because logger is already reading the response?

**Comment by f3ath** [comment]
I see. Going to pass the response body separately.

**Comment by f3ath** [comment]
@uddyami I was not able to reproduce the issue. Could you please post the steps to reproduce in #65

**Comment by uddyami** [comment]
will do
