### ISSUE TITLE
Parse non-standard links

### ISSUE THREAD

**Issue by uddyami** [f3ath/json-api-dart#61]
when i'm trying to parse response that looks like following
```
{
data:{
           type:token,
           id: baseurl/path1/uuid,
           attributes:{
                             label1:value...
           },
           links:{
           link1label: link1
           link2label: link2
           }
       }
}
```

i cannot get links value parsed and stored in `response.data.links`  or `response.document.data.links` .. what m i doing wrong? I get attributes parsed correctly got both data and data in document  `ResourceData` objects. The links don't have `self` and i want check the other values only

EDIT : I found that on Line 170 of `client.dart` has the `links` section but after that it is missing.

**Comment by f3ath** [comment]
I'd need to see an actual JSON the client fails to parse. Feel free to strip out all sensitive data from it, but it has to be a **real well-formatted JSON** in order for me to reproduce the issue.

**Comment by uddyami** [comment]
```
{
   "data":{
      "type":"token",
      "id":"https://example.com/tokens/274d3987-6369-47d9-b37f-a432109103e4",
      "attributes":{
         "access_token":"fbfd35335345dfgdfg334534de1ab467fc3363e77a95f6bb95b9ce149fd2d4493c04a6a88c0f597cdf8f8342359ddd640bfd26064606ab478f",
         "created_at":"2019-12-05T18:26:33.011979Z",
         "expires_at":"2020-01-06T00:26:33.010765Z",
         "refresh_token":"9223543563546fghfghfghe9bf09921732bdedd15eb702ab0800738fd886e60cd69780848012599592e4dec65def60e53d846f9d4e8e41a7a1e89b496286604760"
      },
      "links":{
         "link1":"https://example.com/link1",
         "link2":"https://example.com/path1/50d1d632-cb95-4249-bd27-342342323234"
      }
   }
}
```

**Comment by f3ath** [comment]
This example uses `link` and `link2`, neither of which is mentioned in [v1.0 spec](https://jsonapi.org/format/). The library does not recognize non-standard keys. I can consider adding those non-standard links if there is a good reason for it. One reason I can think of would be if there was a well-known widely-used JSON:API server implementation making use of non-standard links. Would you mind sharing what server this response comes from?

**Comment by f3ath** [comment]
On the other hand, your example is valid according to the [json schema](http://jsonapi.org/schema).

**Comment by uddyami** [comment]
I'm working for small startup and they have have designed api to have multiple custom links to come back in  link section. A few libs server team is looking at apart from documentation are:
https://github.com/Netflix/fast_jsonapi
https://github.com/google/jsonapi

**Comment by f3ath** [comment]
@uddyami Support for non-standard links has been added to [3.0.0-dev.0](https://pub.dev/packages/json_api/versions/3.0.0-dev.0). Please note that this is a development build with a lot of [breaking changes](https://github.com/f3ath/json-api-dart/blob/master/CHANGELOG.md#unreleased), the documentation has not been updated yet. If you're willing to try it out, I'd be thankful for your feedback.

**Comment by f3ath** [comment]
released in https://pub.dev/packages/json_api/versions/3.0.0
