### ISSUE TITLE
Can't get "set-cookie" headers

### ISSUE THREAD

**Issue by alex-misch** [f3ath/json-api-dart#80]
Hello. 
Your `headers` positional argument in any request is type of `Map<Stirng, String>`. But set-cookie can be used twice or more in one request. So it is not valid type for it. Can you change it to `Map<String, List<String>>` ?

**Comment by f3ath** [comment]
This will be implemented in v4 as it's a breaking change.
[EDIT: figured you're talking about the server]

**Comment by f3ath** [comment]
@alex-misch I'm really interested in learning more about your case as I'm actively redesigning  the server. Would you be available for a [quick chat](https://telegram.me/f3ath)?
