### ISSUE TITLE
Export dart_http

### ISSUE THREAD

**Issue by sanekyy** [f3ath/json-api-dart#81]
Hello. 

I started use your package. Thanks for your work.

I use version 4.

I use default Dart HttpClient and wrap it with your DartHttp to pass it into JsonApiClient.

DartHttp is not export from your package. So I have warning of lint.

Fix it please:)

**Comment by f3ath** [comment]
Fixed in [4.0.0-rc.1](https://pub.dev/documentation/json_api/4.0.0-rc.1/client/client-library.html). Please confirm if it works for you.

**Comment by sanekyy** [comment]
I confirm. Thanks for quick response.
