### ISSUE TITLE
Add toString to package entities

### ISSUE THREAD

**Issue by sanekyy** [f3ath/json-api-dart#82]
Hello. Please add toString method to package entities.
For example QueryParameters and ResourseObject.

**Comment by f3ath** [comment]
Please provide:
- the package version
- an example use case

**Comment by sanekyy** [comment]
version: `4.0.0-rc.2`

use cases:

![image](https://user-images.githubusercontent.com/18647037/75375171-9db39f00-58de-11ea-8550-f952961648e8.png)


![image](https://user-images.githubusercontent.com/18647037/75375205-aa37f780-58de-11ea-8a37-4523ae28e10c.png)

**Comment by f3ath** [comment]
OK, I understand this is for logging. Would the [LoggingHttpHandler](https://github.com/f3ath/json-api-dart/blob/v4-dev/lib/src/http/logging_http_handler.dart) solve it?

P.S. feel free to reach out directly on [telegram](https://telegram.me/f3ath)

**Comment by f3ath** [comment]
Closing as solved. Feel free to reopen if needed.
