### ISSUE TITLE
decode json in isolate

### ISSUE THREAD

**Issue by jamesdixon** [f3ath/json-api-dart#89]
First, fantastic package. Cheers.

https://flutter.dev/docs/cookbook/networking/background-parsing

Thoughts?

**Comment by f3ath** [comment]
Thanks for using it. Nice avatar btw :)

It is unclear how much performance gain this might give compared to a) not using isolates at all and b) moving the entire client to an isolate. You are more than welcome to profile it and share the numbers. We can figure out where to go from there.
