### ISSUE TITLE
UTF-8 as default charset for response body decoding

### ISSUE THREAD

**Issue by sanekyy** [f3ath/json-api-dart#94]
JsonApi spec:

https://jsonapi.org/format/#content-negotiation-servers
> Servers MUST send all JSON:API data in response documents with the header Content-Type: application/vnd.api+json without any media type parameters.

Dart HTTP client by default decode use `latin1` charset.

![image](https://user-images.githubusercontent.com/18647037/83067761-e6aaf900-a06f-11ea-825e-0f56b57391b4.png)

So it's not decoding correctly `UTF-8` json:

https://github.com/dart-lang/http/issues/175

Let's use charset `UTF-8` as default.

**Comment by f3ath** [comment]
This is a valid point. Ideally, the decision making and decoding logic should be decoupled in such a way that it can be configured (e.g. set the default encoding) or replaced.

**Comment by f3ath** [comment]
Released https://pub.dev/packages/json_api/versions/4.1.0
